### ISSUE TITLE
Tune intake current sensing parameters

### ISSUE THREAD

**Issue by james-ward** [thedropbears/pystronghold#25]
Is now using call from Talon - should be higher fidelity and better response. Will need retuning. Be careful about different voltage levels in the battery.
Perhaps compare to baseline average instead?

**Comment by ArthurAllshire** [comment]
The ball is currently getting stuck between the intake and either the flywheels or the rails.

**Comment by james-ward** [comment]
The jamming needs to be fixed by the gamepiece section in hardware - it's not a control issue.

**Comment by james-ward** [comment]
Hardware seems reliable - we need to see if we are happy with how it functions with the new velocity approach. We have problems when battery voltage is low - will we ever be this low in a match though?

**Comment by ArthurAllshire** [comment]
Before this gets fixed, if the ball gets stuck in the intake I found that it is easy to nudge the robot towards the intake and the balls inertia will make it hit the intake and start reversing.

**Comment by james-ward** [comment]
I think that what is probably happening is that driving the main wheels is causing a voltage drop, and a subsequent dip in the intake speed. Which means it will have false triggers when we are intaking and driving hard.

**Comment by james-ward** [comment]
Maybe we should combine the approaches - look for a drop in intake speed at the same time that the current goes up?

**Comment by ArthurAllshire** [comment]
This seems to work well at this point, will re-open if necessary.
